config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :rating, :comment, presence: true
  validates :comment, length: { in: 0..200 }
  RATING=[0,1,2,3,4,5]
  validates_inclusion_of :rating, in: RATING


  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  #Associations
  has_many :comments, dependent: :destroy

  KIND=['Fritas', 'Salgados', 'Doces', 'Peixes', 'Saladas']

  # Validations
  validates :name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, presence: true

  # Methods
  def self.created_at
    order(created_at: :DESC)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_recipe

  def index
    @comments = @recipe.comments
  end

  def new
    @comment = @recipe.comments.new
  end

  def create
    @comment = @recipe.comments.new(comment_params)

    if @recipe.save
      redirect_to recipe_comments_path(@recipe), notice: "Comentário criado com sucesso!"
    else
      render :new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :rating, :comment)
  end

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, except: [:index, :new, :create]

  def index
    @recipes = Recipe.created_at
  end

  def update
    if @recipe.save
      @recipe.update(recipe_params)
      redirect_to recipes_path, notice: "Receita alterada com sucesso!"
    else
      render :update
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: "Receita criada com sucesso!"
    else
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, alert: "Receita deletada com sucesso!"
  end

  private
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :stuff, :calories, :prepare_mode, :cost, :kind, :portion, :duration, :poster)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def format_calory(recipe)
    if recipe.calories > 100
      recipe.calories
    else
      content_tag(:strong, 'Light (menos de 100 calorias)')
    end
  end

  def has_image (recipe)
    if recipe.poster.blank?
      image_tag('https://cdn.neemo.com.br/uploads/settings_webdelivery/logo/1630/no-image.png')
    else
      image_tag(recipe.poster)
    end
  end
end

app/views/comments/_form.html.erb
<div class="form-row d-flex justify-content-center px-4 px-md-0 m-0">
  <div class="col-12 col-md-6">
    <%= render 'layouts/errors', object: @comment %>
    <p class="h2">Receita: <b><%= @recipe.name %></b></p>

    <%= form_for ([@recipe, @comment]) do |f| %>
    <div class="form-group mt-3">
      <%= f.label :Nome %>
      <%= f.text_field :name, placeholder: "Insira seu nome", class:"form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Nota_para_a_receita %>
      <%= f.select :rating, options_for_select(Comment::RATING), {prompt: "Selecione sua nota"}, { class: "form-select" } %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Comentário %>
      <%= f.text_area :comment, placeholder:"Redija seu comentário", class:"form-control" %>
    </div>

    <div class="my-3">
      <%= f.submit :Enviar, class:"btn btn-primary" %>
      <%= link_to 'Cancelar', recipes_path, class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>
</div>

app/views/comments/_no_comments.html.erb
<% if @recipe.comments.count == 0 %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Atenção!</strong> Não há comentários para a receita <b><%= @recipe.name %></b>.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/comments/index.html.erb
<div class="d-flex justify-content-center">
  <div class="col-12 col-md-6 px-4 px-md-0">
    <%= render 'no_comments' %>
    <ul class="list-group list-group-flush">
      <% @comments.each do |comment| %>
      <li class="list-group-item p-0">
        <p class="m-0 mt-3">
          <b>Avaliador:</b>
        </p>
        <%= comment.name %>

        <p class="m-0 mt-3">
          <b>Avaliação:</b>
        </p>
        <%= pluralize(comment.rating, 'ponto', 'pontos') %>

        <p class="m-0 mt-3">
          <b>Comentário:</b>
        </p>
        <%= comment.comment %>

        <p class="card-text mt-2"><small class="text-muted">
          Atualizado há
          <%= time_ago_in_words(comment.updated_at) %></small>
        </p>
      </li>
      <% end %>
    </ul>

    <div class="my-3">
      <%= link_to 'Voltar', recipes_path, class: "btn btn-primary" %>
      <%= link_to "Adicionar novo comentário", new_recipe_comment_path(@recipe), class:"btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/_error_alert.html.erb
<% if flash[:alert] %>
<div class="row d-flex justify-content-center m-0">
  <div class="col-12 col-md-6 alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
    <% object.errors.full_messages.each do |m| %>
    <li>
      <%= m %>
    </li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="d-flex justify-content-center px-4 px-md-0" style="background-color: #e3f2fd;">
  <nav class="col-12 col-md-6 navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid p-0">
      <a class="navbar-brand" href="#">Menu</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown link
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_success_alert.html.erb
<% if flash[:notice] %>
<div class="row d-flex justify-content-center m-0">
  <div class="col-12 col-md-6 alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receitas</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>

<body>

  <%= render 'layouts/navbar' %>
  <%= render 'layouts/success_alert' %>
  <%= render 'layouts/error_alert' %>

  <%= yield %>
</body>
</html>

app/views/recipes/_form.html.erb
<div class="form-row d-flex justify-content-center px-4 px-md-0 m-0">
  <div class="col-12 col-md-6">
    <%= render 'layouts/errors', object: @recipe %>

    <%= form_for @recipe do |f| %>
    <div class="form-group mt-3">
      <%= f.label :Nome %>
      <%= f.text_field :name, placeholder: "Insira o nome da receita", class:"form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Ingredientes %>
      <%= f.text_area :stuff, placeholder: "Insira os ingredientes da receita", class:"form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Calorias %>
      <%= f.number_field :calories, placeholder: "Insira o número de calorias da receita", class:"form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Modo_de_preparo %>
    </div>
    <%= f.text_area :prepare_mode, placeholder: "Redija o modo de preparo", cols: 20, rows: 10, class:"form-control" %>

    <div class="form-group mt-3">
      <%= f.label :Custo %>
      <%= f.number_field :cost, placeholder: "Valor total da receita", class:"form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Tipo %>
      <%= f.select :kind, options_for_select(Recipe::KIND), {prompt: "Selecione o tipo de comida"}, { class: "form-select" } %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Porções %>
      <%= f.text_field :portion, placeholder:"Número de porções para servir",class:"form-control" %>
    </div>

    <div class="form-group d-flex mt-3">
      <%= f.label :Tempo_de_preparo %>
    </div>

    <div class="form-group d-flex">
      <%= f.time_select :duration, {prompt: {hour: "Horas", minute: "Minutos"}, time_separator: ""}, {class: "form-select time_style"} %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :Poster %>
      <%= f.text_field :poster, placeholder: ".GIF .JPEG ou .PNG", class:"form-control" %>
    </div>

    <div class="my-3">
      <%= f.submit :Enviar, class:"btn btn-primary" %>
      <%= link_to 'Cancelar', recipes_path, class: "btn btn-danger" %>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="row d-flex justify-content-center px-4 pd-md-0 m-0">
	<div class="col-12 col-md-6 p-md-0">
		<div class="d-flex justify-content-between align-items-center my-3">
			<p class="h1 m-0">Receitas</p>
			<div class="w-100 d-flex justify-content-end align-items-end">
				<p class="m-0">
					<%= link_to "Nova receita" , new_recipe_path, class:"btn btn-primary" %>
				</p>
			</div>
		</div>

		<% @recipes.each do |recipe| %>
		<div class="card mb-3" >
			<div class="row g-0">
				<div class="col-md-8">
					<div class="card-body">
						<h5 class="card-title"><%= recipe.name %></h5>
						<p class="card-text"><%= recipe.prepare_mode %></p>
						<p class="card-text"><small class="text-muted">
							Atualizada no dia
							<%= recipe.updated_at.to_s(:short) %></small>
						</p>
						<%= link_to pluralize(recipe.comments.count, 'comentário', 'comentários'), recipe_comments_path(recipe) %>
					</div>
				</div>
				<div class="card-footer text-muted d-flex justify-content-end">

					<%= link_to "Visualizar" , recipe, class: "btn btn-sm btn-primary" %>
					<%= link_to "Editar" , edit_recipe_path(recipe), class: "btn btn-sm btn-secondary" %>
					<%= link_to "Remover" , recipe_path(recipe), class: "btn btn-sm btn-danger", method: :delete, data:{confirm: "Deseja deletar esta receita?"} %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/recipes/not_found.html.erb
<h1>Página não encontrada</h1>

app/views/recipes/show.html.erb
<div class="row d-flex justify-content-center m-0">
	<div class="col-12 col-md-6 my-3">
		<h1>
			<%= @recipe.name %>
		</h1>

		<div class="mt-3">
			<p class="h4">Ingredientes</p>
			<%= @recipe.stuff %>
		</div>

		<div class="mt-3">
			<p class="h4">Calorias</p>
			<%= @recipe.calories %>
		</div>

		<div class="mt-3">
			<p class="h4">Modo de preparo</p>
			<%= @recipe.prepare_mode %>
		</div>

		<div class="mt-3">
			<p class="h4">Custo</p>
			<%= number_to_currency(@recipe.cost) %>
		</div>

		<div class="mt-3">
			<p class="h4">Tipo</p>
			<%= @recipe.kind %>
		</div>

		<div class="mt-3">
			<p class="h4">Porções</p>
			<%= @recipe.portion %>
		</div>

		<div class="mt-3">
			<p class="h4">Tempo de preparo</p>
			<%= @recipe.duration.strftime("%H:%M") %>
		</div>

		<div class="mt-3">
			<p class="h4">Imagem</p>
			<%= has_image(@recipe) %>
		</div>

		<%= link_to "Voltar" , recipes_path, class:"btn btn-primary my-3" %>
		<%= link_to "Adicionar novo comentário" , new_recipe_comment_path(@recipe), class:"btn btn-secondary my-3" %>
	</div>
</div>